### ISSUE TITLE
Possible bug with summoner.recent_games

### ISSUE THREAD

**Issue by BaconPancakes** [PeterBorah/vigor#33] opened 2014-01-02 07:19 UTC
Hi, 
Great job with the wrapper. I've been using your work and I found a strange error. This _could_ just be my client, but something weird happens when I look up the recent games of "boy54"

```
 summoner = Vigor.summoner 'boy54'
=> #<Vigor::Summoner:0x2704bc0 @fields={:name=>"boy54", :profile_icon_id=>589, :level=>30, :revision_date=>#<DateTime: 45972-11-07T02:56:40+00:00 ((18512299j,10600s,0n),+0s,2299161j)>}, @id=43215051>
```

```
recent_games = summoner.recent_games
NoMethodError: undefined method `map' for nil:NilClass
    from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/vigor-0.5.0/lib/vigor/game.rb:8:in `initialize'
    from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/vigor-0.5.0/lib/vigor.rb:49:in `new'
    from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/vigor-0.5.0/lib/vigor.rb:49:in `block in recent_games'
    from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/vigor-0.5.0/lib/vigor.rb:49:in `map'
    from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/vigor-0.5.0/lib/vigor.rb:49:in `recent_games'
    from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/vigor-0.5.0/lib/vigor/summoner.rb:47:in `recent_games'
    from (irb):94
    from C:/RailsInstaller/Ruby1.9.3/bin/irb:12:in `<top (required)>'
    from -e:1:in `load'
    from -e:1:in `<main>'
```

Just about every other summoner I can think of works fine. Think you can take a look ? Since game data might change before this is reproducible, I did a pastebin of the output from developers.riotgames, in case it helps. http://pastebin.com/bdQRscQ9.

**Comment by PeterBorah** [comment] 2014-01-02 07:28
Thank you for the very thorough bug report! I'll bet there's an edge case I missed. I'll take a look as soon as I get a chance.

**Comment by imogenkinsman** [comment] 2014-01-02 09:57
@BaconPancakes this was caused by https://github.com/PeterBorah/vigor/issues/30 - it was happening when someone played a game that had no other players (you can see a solo custom game in that pastebin).

@PeterBorah just released a new version (with the fix), so this should be fixed once you update your gem. Thanks!

**Comment by PeterBorah** [comment] 2014-01-04 01:32
Closing per @zetsubo's comment. Feel free to reopen if it happens again with the new version!

**Closed as completed by PeterBorah** 2014-01-04 01:32 UTC
